// Walks the exported `dist/` folder and writes a service worker that
// precaches every exported file, so the PWA works fully offline after
// the first load.
const fs = require('fs');
const path = require('path');
const crypto = require('crypto');

const DIST_DIR = path.join(__dirname, '..', 'dist');

function walk(dir, base = dir, files = []) {
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      walk(full, base, files);
    } else {
      const rel = path.relative(base, full).split(path.sep).join('/');
      files.push(rel);
    }
  }
  return files;
}

function main() {
  if (!fs.existsSync(DIST_DIR)) {
    throw new Error(`dist/ not found at ${DIST_DIR} — run the web export first.`);
  }

  const files = walk(DIST_DIR).filter((f) => f !== 'sw.js');
  const urls = files.map((f) => '/' + encodeURI(f));
  if (!urls.includes('/')) urls.push('/');

  const hash = crypto.createHash('sha256').update(urls.join('\n')).digest('hex').slice(0, 12);
  const cacheName = `zenflow-${hash}`;

  const swSource = `// Auto-generated by scripts/generate-sw.js — do not edit by hand.
const CACHE_NAME = ${JSON.stringify(cacheName)};
const PRECACHE_URLS = ${JSON.stringify(urls, null, 2)};

self.addEventListener('install', (event) => {
  event.waitUntil(
    caches.open(CACHE_NAME)
      .then((cache) => cache.addAll(PRECACHE_URLS))
      .then(() => self.skipWaiting())
  );
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys().then((keys) =>
      Promise.all(keys.filter((key) => key !== CACHE_NAME).map((key) => caches.delete(key)))
    ).then(() => self.clients.claim())
  );
});

self.addEventListener('fetch', (event) => {
  const { request } = event;
  if (request.method !== 'GET' || !request.url.startsWith(self.location.origin)) {
    return;
  }

  // SPA navigations: serve the cached shell so routing works offline.
  if (request.mode === 'navigate') {
    event.respondWith(
      fetch(request).catch(() => caches.match('/index.html'))
    );
    return;
  }

  // Cache-first for everything else, with a runtime fallback so files
  // that changed shape (or weren't precached) still get cached going forward.
  event.respondWith(
    caches.match(request).then((cached) => {
      if (cached) return cached;
      return fetch(request).then((response) => {
        if (response.ok) {
          const copy = response.clone();
          caches.open(CACHE_NAME).then((cache) => cache.put(request, copy));
        }
        return response;
      });
    })
  );
});
`;

  fs.writeFileSync(path.join(DIST_DIR, 'sw.js'), swSource);
  console.log(`wrote dist/sw.js precaching ${urls.length} files (cache ${cacheName})`);
}

main();
